version: '3.8'
services:
  dev-db:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5434:54325432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - backend

networks:
  backend:
